baseURL = "https://www.haoxingdu.com"
languageCode = "en-us"
title = "Haoxing DuÔΩúÊùúÊµ©Êòü"
theme = "rocinante"
paginate = 3
summaryLength = 0
publishDir = "docs"
enableGitInfo = true
buildDrafts = false
buildFuture = false
buildExpired = false

[frontmatter]
  lastmod = [":git", "lastmod", "date"]

[markup]
  [markup.highlight]
    style = "monokailight"
    tabWidth = 2
  [markup.goldmark.renderer]
    unsafe= true

[params]
  mainSections = ["post"]
  photo = "/images/me.jpg"
  photoAlt = "Photo of me"
  email = "haoxingdu@gmail.com"
  favicon = "/icon/stabilizer3.jpeg"
  about = """
Hi! I'm **Haoxing**.
I am a [proud](https://www.astralcodexten.com/p/in-continued-defense-of-effective) [effective altruist](https://80000hours.org/podcast/effective-altruism-an-introduction/) working in AI.
I currently work on predicting the weather with AI at [WindBorne](https://windbornesystems.com/), where I also get to [play](https://windbornesystems.com/blog/flying-into-the-eye) with [balloons](https://windbornesystems.com/blog/how-windbornes-self-flying-weather-balloons-navigate-the-sky-to-sense-the-globe).
Previously, I worked on evaluating large language models for dangerous capabilities at [METR](https://metr.org), where we poked at the first AI agents before the term "AI agent" was invented. 
I also did some [research](https://www.lesswrong.com/posts/FF8i6SLfKb4g7C4EL/inside-the-mind-of-a-superhuman-go-model-how-does-leela-zero-2) on neural network interpretability at [Redwood Research](https://www.redwoodresearch.org/).

Before getting into AI I studied theoretical physics.
At Berkeley, I did research in the intersection of machine learning and physics in the amazing [Nachman group](https://nachmangroup.github.io/).
Prior to Berkeley, I was fortunate to be part of the [Perimeter Scholars International](https://perimeterinstitute.ca/psi-masters-program) program, and had the privilege of spending the best college years possible at [Harvey Mudd College](https://www.hmc.edu).

When I'm not thinking about technical topics, I like to read, play video games, make music, [fly](https://www.xcontest.org/world/en/pilots/detail:haoxing) my paraglider, and make very slow progress hiking the [Bay Area Ridge Trail](https://ridgetrail.org/).

I am the happiest wife to [Kasey Markel](https://www.kaseymarkel.com/), and we live in the San Francisco Bay Area.
We have signed the [10% pledge üî∏](https://www.givingwhatwecan.org/pledge).
If you are reading this, please consider doing the same!
 
In a past life, I thought a lot about the foundations of quantum theory.
Although I'm no longer pursuing a career in quantum foundations, I remain passionate about the field, and think that many important, recent ideas in quantum foundations are not being effectively communicated to a wider audience.
I hope the essays below help bridge that gap just a little. 
I also hope that my younger self from undergraduate years would have been inspired if she were to stumble upon these.

"""

  [[params.links]]
    [[params.links.link]]
      name = "Email"
      href = "/contact"
      smart_email_link = true

    [[params.links.link]]
      name = "Google Scholar"
      href = "https://scholar.google.com/citations?user=teOq000AAAAJ&hl=en"
      smart_email_link = false

    [[params.links.link]]
      name = "GitHub"
      href = "https://www.github.com/haoxing-du"
      smart_email_link = false
    
    [[params.links.link]]
      name = "Twitter"
      href = "https://twitter.com/haoxingdu"
      smart_email_link = false
